version: "3.7"
services:
  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - database_data:/data/db
    networks:
      - teste-network

volumes:
  database_data:
    driver: local

networks:
  teste-network: